Devices JSON
wirenboard/wb-device-manager pull request #1
Opened 2022-10-24 06:32 UTC by KraPete

2022-10-24 07:55 UTC, webconn requested changes

2022-10-24 07:55 UTC, webconn commented on README.md
> +            "id": "13453ghh",
Вот тут я бы не стал смешивать id и серийник. Звучит так, как будто серийник - это частный случай id. Например, если у нас в этом списке будет какое-нибудь стороннее устройство без серийника, прописанное в конфиге serial.

2022-10-24 07:55 UTC, webconn commented on README.md
> +            "port": {
Тут нужна сложная структура сразу? почему не string?

2022-10-24 07:55 UTC, webconn commented on README.md
> +            "cfg": {
Это настройки соединения, а могут быть ещё специфические настройки самого устройства

2022-10-24 07:55 UTC, webconn commented on README.md
> +                "has_updates": true
Тут бы ещё написать, до какой версии есть обновление

2022-10-24 07:55 UTC, webconn commented on README.md
> +                "update_progress": 50,
Вот всё про update я бы занёс в отдельный объект, типа

```json
"update": {
  "progress": 50,
  "error": null
}
```

или

```json
"update": null
```
Вдруг мы ещё какую инфу сюда добавим, зачем префиксы плодить

2022-10-24 12:08 UTC, KraPete commented on README.md
> +            "cfg": {
Это настройки устройства, просто сечас там только поля из настройки соединения ;) Я предполагал добавлять сюда, если потребуется

2022-10-24 15:04 UTC, webconn commented on README.md
> +            "port": {
Ещё актуально

2022-10-25 07:56 UTC, webconn approved these changes

2022-10-25 07:56 UTC, webconn commented on README.md
> +            "port": {
Странно, твой ответ не долетел вовремя. Окей, звучит хорошо

2022-10-25 08:13 UTC, KraPete commented on README.md
> +                    "available_fw": "2.2.2"
Тут скорее текст для того, чтобы в интерфейсе написать не просто "есть обновление", а "доступна новая прошивка 2.2.2"

2022-10-25 08:16 UTC, vdromanov commented on README.md
> +            // тип устройства
сюда еще fw_signature надо
и мб device_signature (чтобы матчиться с шаблонами mqtt-serial)

(обе в модбасе лежат)

2022-10-25 08:22 UTC, vdromanov commented on README.md
> +            // тип устройства
и версию бутлоадера (для дебага?)

2022-10-25 08:25 UTC, vdromanov commented on README.md
> +                    "available_fw": "2.2.2"
вот про это и вопрос был, откуда эту версию брать)

тогда - в webui писать "доступна прошивка 1.2.3 (stable)" => нужно смотреть в релиз на контроллере

2022-10-25 08:33 UTC, vdromanov commented on README.md
> +            "type": "MR6C",
а это - та самая странная device_signature, лежащая в модбасе?

2022-10-25 08:55 UTC, KraPete commented on README.md
> +            // тип устройства
Что такое `fw_signature`?
Если можно версию бутлоадера достать, то можно и вывести, и по аналогии с прошивкой обновлять.

2022-10-25 08:55 UTC, KraPete commented on README.md
> +            // прошивка устройства
Можно же всё про бутлоадер отдельной задачей потом сделать.

2022-10-25 08:56 UTC, KraPete commented on README.md
> +                    "available_fw": "2.2.2"
Ну да. Наверное. web-интерфейсу такие тонкости не нужно знать ;)

2022-10-25 08:59 UTC, KraPete commented on README.md
> +            "type": "MR6C",
Вот это надо обсудить. Я так понимаю, что есть человеческое название и какое-то, которое лежит устройстве.
Пока я тут написал то, что в интерфейсе будет выводиться.

2022-11-04 06:34 UTC, sikmir commented on README.md
> +            "serial": "13453ghh",
`serial` как-то сходу ассоциируется с другим, не с серийным номером, может какой-нибудь `sn` или `snid`? SNID часто используется в данном контексте. Чтобы избежать двусмысленности.

2022-11-04 06:49 UTC, sikmir commented on README.md
> +            "in_bootloader": true,
`in_bootloader` сходу звучит непонятно о чем это, если не смотреть на коментарий. Может `is_bootloader` или `bootloader_mode`?

2022-11-04 06:53 UTC, sikmir approved these changes

2022-11-07 06:23 UTC, KraPete commented on README.md
> +            "in_bootloader": true,
Переименовал

2022-11-07 06:23 UTC, KraPete commented on README.md
> +            "serial": "13453ghh",
Переименовал

2022-11-07 07:22 UTC, sikmir approved these changes

2022-11-07 07:32 UTC, webconn commented on README.md
> +        {
Я тут подумал, что нам на первое время (а то и насовсем) есть смысл сюда каждому девайсу положить некий `uuid`, чтобы при формировании RPC-запросов к сервису не приходилось догадываться, какие именно данные об устройстве надо отправить. Подразумевается, что эти UUID остаются валидными как минимум на время сессии с сервисом.

Я просто вижу проблему с тем, что у некоторых устройств (например, у которых нет серийников) поменяется условный ключ в этой структуре, если поменять ему modbus ID. Это вроде не про наши устройства, но мало ли. Плюс, во время обновления структуры может поменяться порядок полей по какой-нибудь причине, и интерфейсу желательно будет сохранять связь между отдельными записями и своим представлением.

В общем, пример может и надуманный, но в любом случае надо либо выделить в уже существующей структуре инварианты для каждого устройства, либо добавить синтетический.

P.S. По этой же причине я бы добавил в корень структуры ID сессии, чтобы после перезагрузки контроллера интерфейс догадался, что существующие у него данные устарели и не надо пытаться понять взаимосвязь между уже нарисованным и тем, что пришло.

2022-11-10 08:19 UTC, vdromanov commented on README.md
> +            "sn": "13453ghh",
Женя предложил добавить сюда еще ts последнего сканирования

2022-11-10 08:36 UTC, webconn commented on README.md
> +            "type": "MR6C",
Решили, посовещавшись, что это будет поле `title`, а ещё надо добавить `fw_sig` и `device_sig`, которые читаются из регистров

2022-11-10 08:40 UTC, webconn commented on README.md
> +        {
Поговорили, может, пока и не нужно

2022-11-10 08:49 UTC, webconn commented on README.md
> +        {
На обсуждении всё-таки решили внедрить

2022-11-10 08:59 UTC, webconn commented on README.md
> +            "sn": "13453ghh",
Поддерживаю

2022-11-10 09:05 UTC, vdromanov commented on README.md
> +            // тип устройства
добавляем только fw_signature

2022-11-10 09:08 UTC, vdromanov requested changes
насколько я понял, осталось добавить устройству:

- uuid. Будет генерироваться бекендом. Снаружи будут запросы вида "сделай что-нибудь с девайсом UUID=N"
- fw_signature, device_signature
- title. Будет какое-то человекочитаемое название, получающееся из device_signature внутренней магией
- ts последнего сканирования

2022-11-11 09:34 UTC, webconn commented on README.md
> +            "uuid": "bb2b49a5",
У UUID в целом довольно специальный формат:
`123e4567-e89b-12d3-a456-426655440000`

2022-11-11 09:34 UTC, webconn commented on README.md
> +            "last_scan": 1668154795454,
Я бы назвал это `last_seen`, чтобы нормально выглядело для устройств, полученных не из конфига serial. И надо сразу решить, как будет выглядеть значение для тех устройств, которые есть в конфиге, но не отвечают. Предлагаю `null`, и чтобы поле всегда тут было для всех устройств

2022-11-11 09:37 UTC, KraPete commented on README.md
> +            "uuid": "bb2b49a5",
Может в привычном формате `123e4567-e89b-12d3-a456-426655440000` ? Или это посто число уникальное?

2022-11-15 00:15 UTC, vdromanov commented on README.md
> +            "last_scan": 1668154795454,
готово

2022-11-15 00:15 UTC, vdromanov commented on README.md
> +            "uuid": "bb2b49a5",
готово

2022-11-15 00:17 UTC, vdromanov approved these changes
думаю, можно вливать
в соседнем пр (прототип) - всё соответствует

2022-11-15 04:11 UTC, merged