Feature/first prototype
wirenboard/wb-device-manager pull request #2
Opened 2022-11-01 07:53 UTC by vdromanov

потроха для сканирования щины через новый модбас
под капотом всё проверяет minimalmodbus

2022-11-01 08:09 UTC, vdromanov commented on wb_device_manager/serial_bus.py
> +        number_of_bytes_to_read = 1000  # we need relatively huge one
мы не знаем точный размер ответа (сколько девайсы будут думать, и в шину лететь FF во время арбитража)

=> мб в сериал ручку добавить "response_size = -1", а то неочевидно

2022-11-01 08:10 UTC, vdromanov commented on wb_device_manager/serial_bus.py
> +        number_of_bytes_to_read = 1000  # we need relatively huge one
у сериала - поведение "в шину перестало лететь - возвращаем" - работает и сейчас

2022-11-02 10:05 UTC, webconn reviewed
Пока только до оформления докопался, хочу дождаться решения с отправкой json

2022-11-02 10:05 UTC, webconn commented on wb-device-manager
> +if __name__ == "__main__":
Вот это всё в модуль в `main()`, тут только вызов оного

2022-11-02 10:05 UTC, webconn commented on wb_device_manager/serial_bus.py
> +class ExtendedMBusScanner:
Сэкономил две буквы и в итоге это уже другой протокол, [m-bus.com](https://m-bus.com)

2022-11-04 06:05 UTC, sikmir commented on wb-device-manager
> +if __name__ == "__main__":
Да,  и когда это в модуле в `main()`,  этот скрипт вообще можно убрать, а добавить в `setup.py`:
```py
      entry_points={
        'console_scripts': [
          'wb-device-manager=wb_device_manager.main:main'
        ]
      }
```
Тогда при сборке он сам сгенерится.

2022-11-04 06:35 UTC, webconn commented on wb-device-manager
> +if __name__ == "__main__":
Стоит отметить, что питон такие скрипты делает очень тяжеловесными, они на наших контроллерах запускаются сильно дольше самодельных

2022-11-04 20:12 UTC, sikmir commented on wb-device-manager
> +if __name__ == "__main__":
Похоже этой проблемы уже нет начиная с Python 3.8 и setuptools 47.2. Там причина была в том, что сгенеренный скрипт импортировал `pkg_resources`.

2022-11-05 06:45 UTC, webconn commented on wb-device-manager
> +if __name__ == "__main__":
Я вроде как с 3.10 собирал...

2022-11-09 13:00 UTC, vdromanov commented on wb_device_manager/__init__.py
> +#!/usr/bin/env python3
готово

2022-11-09 13:00 UTC, vdromanov commented on wb_device_manager/serial_bus.py
> +class ExtendedMBusScanner:
готово
назвал длинно и страшно

2022-11-09 13:01 UTC, vdromanov commented on wb-device-manager
> +if __name__ == "__main__":
c setup.py ничего не делал; только убрал в main

2022-11-09 13:21 UTC, vdromanov commented
продублирую контекст:

[хотелки в миро](https://miro.com/app/board/uXjVPM_Rg2M=/)
прототип; сейчас - сканирует шину через новый modbus; отдает, что насканировал в статус-топик mqtt

как погонять:

- нужен wb-mqtt-serial 2.74+
- устройства с новым modbus (wb-led с последней прошивкой, например)
- `mosquitto_sub -t '/rpc/v1/wb-device-manager/#' -v`
- `mosquitto_pub -t '/rpc/v1/wb-device-manager/bus_scan/scan/test_client' -m '{"id" : "1", "params" : {}}'`

всё установлено на 0.244

2022-11-09 13:24 UTC, vdromanov commented on wb/device_manager/__init__.py
> +shutdown_event = Event()  # signals all long-running threads to stop
если что-то из thread_pool начало работать - остановить это уже нельзя (и не рекомендуется) => долгие воркеры смотрят сюда

2022-11-09 13:26 UTC, vdromanov commented on wb/device_manager/main.py
> +            self.mqtt_connection.publish(state_topic, self.state_json(), retain=True)
выражаю обеспокоенность: уже на 3х девайсах debug mqtt говорит о летающих json-ах на 2кб

=> предлагаю: для интерактивности сделать отдельный топик с прогрессом; слать весь state - только по его изменению

2022-11-09 13:27 UTC, vdromanov commented on wb/device_manager/mqtt_rpc.py
> +    MESSAGE = "Task is already executing"
по задумке - нельзя запустить одновременно 2 долгих задачи (одинаковые topic и payload)

2022-11-09 13:31 UTC, vdromanov commented on wb/device_manager/mqtt_rpc.py
> +    def add_to_processing(self, mqtt_message):
смотрим, не пытаются ли запустить две одинаковых задачи

казалось бы, решается queue, но всё равно придётся лезть под капот для реализации сравнения задач => сейчас выглядит, как будто достаточно

2022-11-09 13:36 UTC, vdromanov commented on wb/device_manager/mqtt_rpc.py
> +    def run_async(self, message):
если мы жуём долгий коллбек, и внутри него хотим что-то слать в mqtt - это не работает, т.к. paho-mqtt в одном потоке смотрит в сеть и запускает коллбеки

=> интернеты говорят, что каноничный способ - ввести каких-нибудь воркеров, что и реализовано через concurrent.futures и ThreadPoolExecutor

2022-11-09 13:37 UTC, vdromanov commented on wb/device_manager/mqtt_rpc.py
> +    def run_async(self, message):
вообще, навскидку долгими задачами выглядят: сканирование устройств, обновление прошивки, разрешение коллизий slaveid

2022-11-09 13:39 UTC, vdromanov commented on wb/device_manager/mqtt_rpc.py
> +        if self.is_processing(message):
тут еще, на самом деле, можно ругнуться, если все воркеры заняты. И мб даже не ставить задачу

под капотом у ThreadPoolExecutor - бесконечная queue => снаружи выглядит, как задача поставилась, а когда что-то начнется - непонятно

2022-11-09 16:35 UTC, vdromanov commented
От Жени - добавлять к девайсу ts последнего сканирования

2022-11-10 06:57 UTC, sikmir commented on debian/control
> +Build-Depends: dh-python, debhelper (>= 10), python3, python3-setuptools, python3-wb-mcu-fw-updater
Еще `python3-mosquitto` нужен.

2022-11-10 09:24 UTC, vdromanov commented on wb/device_manager/main.py
> +            self.mqtt_connection.publish(state_topic, self.state_json(), retain=True)
обсудили - пока не стоит беспокоиться

но:
убрать отступы, слать json одной строчкой

2022-11-14 23:47 UTC, vdromanov commented on wb/device_manager/main.py
> +            self.mqtt_connection.publish(state_topic, self.state_json(), retain=True)
готово

2022-11-15 00:06 UTC, vdromanov commented on wb/device_manager/mqtt_rpc.py
> +        if self.is_processing(message):
готово

2022-11-15 00:09 UTC, vdromanov commented on debian/control
> +Build-Depends: dh-python, debhelper (>= 10), python3, python3-setuptools, python3-wb-mcu-fw-updater
предполагаю, нужен не москит, а paho-mqtt (на ноуте без python3-mosquitto собирается отлично)

добавил python3-paho-mqtt

2022-11-15 00:20 UTC, vdromanov commented on wb/device_manager/main.py
> +    def publish_state(self):  # TODO: an observer pattern; on_change callbacks
в веточке уже есть

шлёт в mqtt на обновление каждого поля state

2022-11-17 07:31 UTC, webconn requested changes
Я начал рассматривать с мелочей, а потом нашёл принципиальный момент про внутренность RPC-вызова `scan`.

Думаю, нам стоит внутри команды собраться и порисовать примеры приложений и как вообще делается их архитектура

2022-11-17 07:31 UTC, webconn commented on wb/device_manager/main.py
> +        ("bus_scan", "scan") : lambda: DeviceManager(state_topic).scan_serial_bus(
Я тут не такого хотел. Насколько я понял, сейчас при вызове RPC `bus_scan.scan` у тебя запускается процедура сканирования, и пока она не закончится, RPC не вернётся. Изначально хотелось, чтобы это был просто триггер: "начни сканирование" - "хорошо" - (клиент подписывается на топик состояния и слушает, что там происходит).

2022-11-22 17:17 UTC, vdromanov commented on wb/device_manager/__init__.py
> +shutdown_event = Event()  # signals all long-running threads to stop
обсудили-посмотрели: кажется, причина - блокирующий communicate в minimalmodbus

решили завезти асинхронность

2022-11-22 17:17 UTC, vdromanov commented on debian/wb-device-manager.service
> +After=wb-mqtt-serial.service
готово
копипаста закралась, кажется

2022-11-22 17:17 UTC, vdromanov commented on debian/wb-device-manager.service
> +ExecStart=/usr/bin/wb-device-manager
готово

2022-11-22 17:17 UTC, vdromanov commented on tests/busscanner_test.py
> +        ret = minimalmodbus._hexdecode(response_hex_str)
у нас же уже свой minimalmodbus

2022-11-22 17:17 UTC, vdromanov commented on tests/busscanner_test.py
> +if __name__ == '__main__':
а это вообще оказалось не нужно!

2022-11-22 17:17 UTC, vdromanov commented on wb/device_manager/main.py
> +        ("bus_scan", "scan") : lambda: DeviceManager(state_topic).scan_serial_bus(
по архитектуре - обсудили и решили завезти асинхронности (отдельно)

есть веточка и тикет

2022-11-23 08:51 UTC, webconn commented on tests/busscanner_test.py
> +        ret = minimalmodbus._hexdecode(response_hex_str)
Ну а какая разница. Если это нужно в публичном API, надо его туда и класть. А так однажды кто-то из нас пойдёт править `minimalmodbus`, решит по `_`, что метод приватный, и избавится от него или переименует, а тут всё сломается.

2022-11-24 22:35 UTC, vdromanov commented
не собирается, т.к. updater v1.7.0 с public api minimalmodbus еще не заехал

2022-11-24 22:36 UTC, vdromanov commented on tests/busscanner_test.py
> +        ret = minimalmodbus._hexdecode(response_hex_str)
обсудили в телеге; сделал public api minimalmodbus'у

2022-11-25 15:27 UTC, sikmir commented
> не собирается, т.к. updater v1.7.0 с public api minimalmodbus еще не заехал

https://github.com/wirenboard/wb-mcu-fw-updater/pull/36

2022-11-28 06:25 UTC, webconn commented
Для истории - мы решили двигаться в сторону решения на основе asyncio, параллельно адаптируя библиотеку wb_modbus к работе с корутинами. Чтобы сейчас сделать итерацию, будем использовать функции из `minimalmodbus`, потому что пока что они лежат ближе. `minimalmodbus` плохо подходит в качестве библиотеки при переходе на asyncio, потому что абстракция последовательного порта там закопана глубоко внутри и придётся всё переписывать для добавления `async`/`await`

2022-12-02 04:20 UTC, webconn reviewed
Перезапроси ревью, когда async-версия будет здесь

2022-12-20 05:24 UTC, KraPete reviewed
Можно ещё в Readme.md добавить описание запросов и ответов RPC?

2022-12-23 06:34 UTC, webconn approved these changes

2022-12-24 12:28 UTC, evgeny-boger commented on tests/busscanner_test.py
> +        }
ммм, копипаста.

```python
timeouts = {baud: minimalmodbus._calculate_minimum_silent_period(baud) for baud in ALLOWED_BAUDRATES}
```
?

2022-12-26 08:12 UTC, sikmir approved these changes

2022-12-26 08:40 UTC, merged