add fields is_ext_scan and ports_to_scan to json contract
wirenboard/wb-device-manager pull request #23
Opened 2023-02-06 08:24 UTC by vdromanov

здес - пункты 1.1 и 4
всё остальное - может делать фронт из приходящих данных

![2023-02-06_11-23-19](https://user-images.githubusercontent.com/25829054/216921040-fcc4009c-388e-4f49-a9e4-7b428568787d.png)

2023-02-06 09:10 UTC, webconn approved these changes
lgtm, только версию ещё поправить

2023-02-06 09:22 UTC, webconn commented
Это ещё требует доработки на фронте, и не хватает параметров соединений, так что отзываю свой аппрув

2023-02-06 15:18 UTC, vdromanov commented
добавил настройки связи рядом с портом
+ причесал, насколько возможно

2023-02-07 06:28 UTC, sikmir requested changes

2023-02-07 06:28 UTC, sikmir commented on README.md
>      "scanning_port": "/dev/ttyRS485-1 9600 8N1",
`scanning_port` теперь можно вообще удалить.

2023-02-07 06:28 UTC, sikmir commented on wb/device_manager/main.py
> +            debug_port_records.extend(
Это не надо как раз, в `ports_to_scan` нам нужны только порты сканируемые в данный момент, а не все которые будут сканироваться.

2023-02-07 06:28 UTC, sikmir commented on README.md
> +    // порты (с настройками связи), на которых будет производиться (или уже идёт) сканирование
```suggestion
    // порты (с настройками связи), на которых в данный момент идёт сканирование
```

2023-02-07 06:28 UTC, sikmir commented on README.md
> +    "ports_to_scan": ["/dev/ttyRS485-1 9600 8N1", "/dev/ttyRS485-2 9600 8N1"],
```suggestion
    "scanning_ports": ["/dev/ttyRS485-1 9600 8N1", "/dev/ttyRS485-2 9600 8N1"],
```

2023-02-07 10:53 UTC, vdromanov commented on README.md
>      "scanning_port": "/dev/ttyRS485-1 9600 8N1",
готово

2023-02-07 10:53 UTC, vdromanov commented on wb/device_manager/main.py
> +            debug_port_records.extend(
готово

2023-02-07 10:53 UTC, vdromanov commented on README.md
> +    // порты (с настройками связи), на которых будет производиться (или уже идёт) сканирование
готово

2023-02-07 10:53 UTC, vdromanov commented on README.md
> +    "ports_to_scan": ["/dev/ttyRS485-1 9600 8N1", "/dev/ttyRS485-2 9600 8N1"],
готово

2023-02-07 11:42 UTC, sikmir approved these changes

2023-02-07 12:33 UTC, merged