Fix scanning devices with old firmware using 2 stopbits
wirenboard/wb-device-manager pull request #26
Opened 2023-02-09 14:25 UTC by sikmir

Поправил порядок сканирования, теперь такой:
```
115200 8N2
9600 8N2
57600 8N2
115200 8N1
9600 8N1
57600 8N1
1200 8N2
2400 8N2
4800 8N2
19200 8N2
38400 8N2
1200 8N1
2400 8N1
4800 8N1
19200 8N1
38400 8N1
115200 8O2
9600 8O2
57600 8O2
115200 8O1
9600 8O1
57600 8O1
1200 8O2
2400 8O2
4800 8O2
19200 8O2
38400 8O2
1200 8O1
2400 8O1
4800 8O1
19200 8O1
38400 8O1
115200 8E2
9600 8E2
57600 8E2
115200 8E1
9600 8E1
57600 8E1
1200 8E2
2400 8E2
4800 8E2
19200 8E2
38400 8E2
1200 8E1
2400 8E1
4800 8E1
19200 8E1
38400 8E1
```

2023-02-09 18:59 UTC, vdromanov commented on wb/device_manager/main.py
> +                for bd in bds[:3]:
думаю - надо как-то обозвать
из серии most_frequent_bds, less_frequent_bds

2023-02-09 19:04 UTC, vdromanov commented on wb/device_manager/main.py
> +                2,
тут еще - надо спросить в чатике "мы два стопбита считаем дефолтными или один (в случае, когда они неважны)" 
(я - не знаю)

вроде как, исторически - были 2 стопбита (и первые пользователи DM смущались, когда видели один)
но когда пилили прототип DM - кто-то захотел, чтобы был один

спроси на всякий случай, наверное...

2023-02-09 19:04 UTC, vdromanov commented on wb/device_manager/main.py
>      def _get_all_uart_params(
хочется докстринг, в котором написано, зачем мы делаем такую хитрую магию

2023-02-09 19:05 UTC, vdromanov requested changes
хочется:

1) Расписать, зачем мы это делаем. Происходит магия, и через время - неизбежно возникнут вопросы "а зачем?"
2) Тест, что последовательность - именно такая, как в описании PR

2023-02-09 19:05 UTC, sikmir commented on wb/device_manager/main.py
> +                for bd in bds[:3]:
готово

2023-02-10 07:51 UTC, sikmir commented on wb/device_manager/main.py
>      def _get_all_uart_params(
добавил

2023-02-10 07:52 UTC, sikmir commented
> хочется:
> 
>     1. Расписать, зачем мы это делаем. Происходит магия, и через время - неизбежно возникнут вопросы "а зачем?"
> 
>     2. Тест, что последовательность - именно такая, как в описании PR

добавил тест и комент

2023-02-10 08:26 UTC, vdromanov approved these changes
погонял на 1.202; вопросов не имею

(кроме идеологического про 1/2 стопбита)

2023-02-10 08:55 UTC, merged