Use mqtt client wrapper from wb-common
wirenboard/wb-device-manager pull request #27
Opened 2023-03-01 13:51 UTC by sikmir

Depends on https://github.com/wirenboard/wb-common/pull/8

Test instructions:
```sh
$ wb-device-manager -b unix:///var/run/mosquitto/mosquitto.s
[INFO] Registered to atexit hook: close unix:///var/run/mosquitto/mosquitto.sock
[INFO] Mqtt: reconnect to unix:///var/run/mosquitto/mosquitto.sock -> 0
$ wb-device-manager -b tcp://127.0.0.1:1883
[INFO] Registered to atexit hook: close tcp://127.0.0.1:1883
[INFO] Mqtt: reconnect to tcp://127.0.0.1:1883 -> 0
$ wb-device-manager -b ws://127.0.0.1:18883
[INFO] Registered to atexit hook: close ws://127.0.0.1:18883
[INFO] Mqtt: reconnect to ws://127.0.0.1:18883 -> 0
$ mqtt-rpc-client -d wb-device-manager -s bus-scan -m Start
'Ok'
```

2023-03-03 07:32 UTC, webconn requested changes

2023-03-03 07:32 UTC, webconn commented on debian/control
> +Build-Depends: dh-python, debhelper (>= 10), python3-all, python3-setuptools, python3-wb-common (>= 2.1.0), python3-wb-mcu-fw-updater, python3-mqttrpc (>= 1.1.5)
В обычные зависимости оно потом попадает, проверил?
А ещё тут остаётся явная зависимость от `paho-mqtt`, ниже есть `topic_matches_sub`

2023-03-03 07:32 UTC, webconn commented on wb/device_manager/main.py
> +        "--broker",
Надо алиас на старый аргумент оставить, мало ли где в скриптах осталось у кого-то

2023-03-03 13:45 UTC, sikmir commented on wb/device_manager/main.py
> +        "--broker",
добавил алиас, но опять же это сервис, нигде в скриптах не должен использоваться

2023-03-03 13:46 UTC, sikmir commented on debian/control
> +Build-Depends: dh-python, debhelper (>= 10), python3-all, python3-setuptools, python3-wb-common (>= 2.1.0), python3-wb-mcu-fw-updater, python3-mqttrpc (>= 1.1.5)
Добавил paho-mqtt

2023-03-03 14:03 UTC, sikmir commented on debian/control
> +Build-Depends: dh-python, debhelper (>= 10), python3-all, python3-setuptools, python3-wb-common (>= 2.1.0), python3-wb-mcu-fw-updater, python3-mqttrpc (>= 1.1.5)
> В обычные зависимости оно потом попадает, проверил?

Кстати да, они изначально не туда прописаны:
```
$ apt-cache depends wb-device-manager
wb-device-manager
  Depends: <python3:any>
    python3
  Depends: python3-mqttrpc
  Depends: wb-mqtt-serial
  Depends: python3-wb-mcu-fw-updater
  Breaks: <python3-wb-device-manager>
  Recommends: wb-mqtt-homeui
  Replaces: <python3-wb-device-manager>
    wb-device-manager
```

2023-03-03 14:33 UTC, sikmir commented on debian/control
> +Build-Depends: dh-python, debhelper (>= 10), python3-all, python3-setuptools, python3-wb-common (>= 2.1.0), python3-wb-mcu-fw-updater, python3-mqttrpc (>= 1.1.5)
Продублировал в Depends

2023-03-06 07:22 UTC, webconn approved these changes

2023-03-06 07:25 UTC, merged