Feature/60014 mge
wirenboard/wb-device-manager pull request #30
Opened 2023-08-31 15:15 UTC by vdromanov

Хотели узнать, работает ли быстрый модбас через mge. Работает!

Но в device-manager-е поддержкой сканирования через mge и не пахло.
Концептуально: для mge появился tcp-инструмент, который подсовывает порт и ip в rpc-запрос сериалу.
Вытащил инструмент наружу, где надо.
Для tcp-портов снаружи нет serial настроечек (а видеть их хочется) => вычитываем с устройств

собрал на коленке всякого интересного (2 mge)
![image](https://github.com/wirenboard/wb-device-manager/assets/25829054/c6ab93d8-4717-4a1f-a9c9-3bb3948175d2)

2023-09-01 06:36 UTC, webconn requested changes

2023-09-01 06:36 UTC, webconn commented on wb/device_manager/main.py
> +        do_read_serial_params_from_device = issubclass(instrument, mqtt_rpc.AsyncModbusInstrumentTCP)
Абстракции протекли. Лучше бы узнавать это непосредственно от сканера (например, сканер из tcp должен вычитывать данные из устройств, а локальный может просто константы возвращать).

И инструмент как-то странно сюда затёк, вроде без него можно обойтись, делегировав сканеру выгрузку данных из устройства (как я выше и предлагаю)

2023-09-01 06:36 UTC, webconn commented on wb/device_manager/main.py
> +        do_read_serial_params_from_device = issubclass(instrument, mqtt_rpc.AsyncModbusInstrumentTCP)
Абстракции протекли. Лучше бы узнавать это непосредственно от сканера (например, сканер из tcp должен вычитывать данные из устройств, а локальный может просто константы возвращать).

И инструмент как-то странно сюда затёк, вроде без него можно обойтись, делегировав сканеру выгрузку данных из устройства (как я выше и предлагаю)

2023-09-01 06:36 UTC, webconn commented on wb/device_manager/main.py
> +    async def fill_serial_params(self, device_info, mb_conn):
Вот этой штуке как будто место в реализациях сканеров (для MGE такая, для локального просто из констант)

2023-09-18 11:56 UTC, vdromanov commented on wb/device_manager/main.py
> +    async def fill_serial_params(self, device_info, mb_conn):
готово

2023-09-18 11:56 UTC, vdromanov commented on wb/device_manager/main.py
> +        do_read_serial_params_from_device = issubclass(instrument, mqtt_rpc.AsyncModbusInstrumentTCP)
готово

2023-09-18 11:57 UTC, vdromanov commented
поправил абстракций

2023-09-19 11:19 UTC, webconn reviewed
Архитектурно стало лучше, way to go!

2023-09-19 11:19 UTC, webconn commented on tests/main_test.py
> +        self.uart_params_mapping = {}
тут никакой `super().__init__()` не потерялся?

2023-09-19 11:19 UTC, webconn commented on wb/device_manager/serial_bus.py
> +                    {f"{slaveid}-{sn}": uart_params}
Ключ можно через tuple сделать, чтобы такими чудесами не страдать. И вообще, нужен ли там slaveid?

2023-09-19 11:19 UTC, webconn commented on wb/device_manager/main.py
> +        return {"serial": serial_ports, "tcp": tcp_ports}
Не очень нравится, что это в словаре. Думаю, список однотипных записей вроде `('tcp', params) и `('serial', params)` (а ещё лучше namedtuple) подошёл бы лучше, так их в случае чего можно дальше передавать и не путаться

2023-09-20 07:48 UTC, vdromanov commented on tests/main_test.py
> +        self.uart_params_mapping = {}
он тут наоборот не нужен

так моки здесь устроены, чтобы mqtt не тянуть и тд

2023-09-20 07:48 UTC, vdromanov commented on wb/device_manager/serial_bus.py
> +                    {f"{slaveid}-{sn}": uart_params}
отличная идея!
slaveid здесь как минимум не мешает, а еще - спасёт от коллизии серийников; оставил

готово

2023-09-20 07:48 UTC, vdromanov commented on wb/device_manager/main.py
> +        return {"serial": serial_ports, "tcp": tcp_ports}
а еще лучше - датакласс)
т.к. у namedtuple default-поля некрасиво делаются

сделал с dataclass

2023-09-21 07:56 UTC, webconn commented on wb/device_manager/main.py
> +        return {"serial": serial_ports, "tcp": tcp_ports}
Не, ты меня не совсем понял. Я не хотел делать словарь из списков, я хотел список из словарей :)

2023-09-21 08:42 UTC, webconn commented on wb/device_manager/main.py
> +        return {"serial": serial_ports, "tcp": tcp_ports}
Поговорили лично, решили оставить как есть, очевидных преимуществ нет

2023-09-21 08:43 UTC, vdromanov commented on wb/device_manager/main.py
> +        return {"serial": serial_ports, "tcp": tcp_ports}
в телеге обсудили - решили датакласс оставить

2023-09-21 08:45 UTC, webconn approved these changes

2023-09-21 08:45 UTC, webconn commented on tests/main_test.py
> +        self.uart_params_mapping = {}
Неправильно это всё, конечно, ну ладно

2023-09-25 08:29 UTC, vdromanov commented
вливаю; врядли что-то конструктивное прилетит еще

2023-09-25 08:29 UTC, merged