Feature/concurrent modbus
wirenboard/wb-device-manager pull request #4
Opened 2022-11-24 07:58 UTC by vdromanov

заехал asyncio:
- по логам видно, что порты сканируются конкуррентно
- debug-mode даже не ругается

основная идея - разбить блокирующий communicate (посылаем rpc-запрос -> ждем ответа) на отдельные отправку запроса и ожидание ответа
для этого понадобился (как минимум) асинхронный `MQTTRPCResponseManager` (сейчас - копипастой из `mqttrpc`)

ближайший план - вытащить из `mqttrpc` ручки для обеспечения асинхронности; подумать, что делать с `wb_modbus.bindings` (сейчас - запускается на executor'e; благо - надо немного, где)

2022-11-28 22:13 UTC, vdromanov commented
сделал, что обсуждали в телеге
![2022-11-29_01-06-22](https://user-images.githubusercontent.com/25829054/204391273-d5b0e3b7-4d36-49fa-99e0-21b1ea66f65e.png)

2022-11-29 05:18 UTC, webconn requested changes
Вообще мне нравится то, что стало получаться

2022-11-29 05:18 UTC, webconn commented on wb/device_manager/mqtt_rpc.py
> +            "response_timeout": round(self.serial.timeout * 1E3),
`1000` читается лучше, чем `1E3` (от создателей 2к22)

2022-11-29 05:18 UTC, webconn commented on wb/device_manager/mqtt_rpc.py
> +    MAX_CONCURRENT_TASKS = 10  # TODO: make a performance research
Точно ли нам в принципе сейчас нужно это ограничение?

2022-11-29 05:18 UTC, webconn commented on wb/device_manager/mqtt_rpc.py
> +    async def publish_overall_state(self):
Этому по-моему тоже место в `DeviceManager`, это ж бизнес-логика

2022-11-29 05:18 UTC, webconn commented on wb/device_manager/main.py
> +        async for port in self._get_ports():
Мы ж тут хотели сделать `gather`, чтобы несколько портов параллельно сканировались

2022-11-29 05:18 UTC, webconn commented on wb/device_manager/main.py
> +            await self.publish_state()
Я думаю, это можно почаще делать, типа с каждым найденным устройством

2022-11-29 05:18 UTC, webconn commented on wb/device_manager/__init__.py
> +def make_async(func):
Кажется, это больше не нужно

2022-11-29 23:48 UTC, vdromanov commented on wb/device_manager/__init__.py
> +def make_async(func):
убрал

2022-11-29 23:48 UTC, vdromanov commented on wb/device_manager/main.py
> +            await self.publish_state()
готово

2022-11-29 23:48 UTC, vdromanov commented on wb/device_manager/main.py
> +        async for port in self._get_ports():
готово

что-то с gather плохо работало: симптомы - в state добавляются предыдущие настроечки (в отличие от тех, на которых было сосканированно устройство); предполагаю, из-за того, что у нас происходит переключение контекста внутри сканирования

заработало только с мутексом
изменения времени сканирования - не заметил; параллельно ходить в модбас - тоже можно

2022-11-29 23:48 UTC, vdromanov commented on wb/device_manager/mqtt_rpc.py
> +    async def publish_overall_state(self):
готово

2022-11-29 23:48 UTC, vdromanov commented on wb/device_manager/mqtt_rpc.py
> +    MAX_CONCURRENT_TASKS = 10  # TODO: make a performance research
вроде бы не нужно; убрал

2022-11-29 23:48 UTC, vdromanov commented on wb/device_manager/mqtt_rpc.py
> +            "response_timeout": round(self.serial.timeout * 1E3),
готово

2022-11-29 23:48 UTC, vdromanov commented on wb/device_manager/mqtt_rpc.py
> +class MQTTConnManager(metaclass=Singleton):  # TODO: split to common lib
готово

2022-11-29 23:48 UTC, vdromanov commented on wb/device_manager/mqtt_rpc.py
> +STATE_PUBLISH_QUEUE = asyncio.Queue()
готово

2022-11-29 23:48 UTC, vdromanov commented on wb/device_manager/mqtt_rpc.py
> +class Singleton(type):
готово
убрал везде

2022-12-01 06:27 UTC, KraPete requested changes
1. Поставил wb-device-manager, запустил сканирование. RPC вернул результат только после полного завершения сканирования. Мы ж договаривались о другом. Что это просто триггер для начала сканирования. Вернуть ответ оно должно сразу, что начало, или не могу, или уже и так в процессе. Внутри по триггеру запустится процесс сканирования и будет в статусе отражаться. Кстати, процесс в статусе отражается.
2. Топик `/rpc/v1/wb-device-manager/bus-scan/state` лежит в ветке `/rpc`. Мы не хотим его вынести в `/devices` или куда-то ещё? Оно ж не про RPC.

2022-12-01 06:34 UTC, KraPete commented
3. Запустил сканирование на контроллере, к которому ничего не подключено. Запускал несколько раз подряд. Один из запусков завершился, но в топике `status` осталось `{ progress: 96, scanning: true, devices: [] }`

2022-12-01 06:57 UTC, KraPete commented
4. Сервис не чистит за собой топики при остановке

2022-12-01 08:04 UTC, vdromanov commented
статус на сейчаc:

есть чек-лист на погонять
надо поправить ответ сразу на запуск долгой таски

2022-12-01 08:31 UTC, KraPete commented
5. У нас везде RPC методы названы с заглавной буквы. Вероятно, надо сделать `/rpc/v1/wb-device-manager/bus-scan/State` и `/rpc/v1/wb-device-manager/bus-scan/Scan`

2022-12-01 09:11 UTC, webconn reviewed
Про чеклист

2022-12-01 09:11 UTC, webconn commented on tests/checklist.md
> +* пакет успешно устанавливается на WB с релизом > wb-2207; **не** устанавливается на <= wb-2207
Требование "не устанавливаться на старых релизах" странное, тогда надо прям где-то явно запрет прописывать

2022-12-01 09:11 UTC, webconn commented on tests/checklist.md
> +### Интерфейс rpc наружу
Не хватает требований к хорошим случаям, в частности тех, что были в комментариях от @KraPete

2022-12-01 10:27 UTC, webconn requested changes
Важно сейчас учесть то, про что Пётр сказал, причём не забыв это внести в чеклист

2022-12-01 10:27 UTC, webconn commented on wb/device_manager/mqtt_rpc.py
> +        self.mqtt_connection.disconnect()
По-моему, делать `disconnect` после `loop_stop` бессмысленно, потому что пакет наружу не уйдёт. Абсолютно правильная последовательность - делать `disconnect`, потом дожидаться вызова `on_disconnect`, после этого `loop_stop`. (Кстати, хорошо вписывается в концепцию асинхронки).

Думаю, в нашем случае можно послать `disconnect` просто до `loop_stop`.

2022-12-01 21:53 UTC, vdromanov commented on wb/device_manager/main.py
> +    STATE_PUBLISH_TOPIC = "/rpc/v1/wb-device-manager/bus-scan/state"
готово

2022-12-01 21:53 UTC, vdromanov commented on wb/device_manager/main.py
> +            async with self.state_correctness_lock:
убрал мутексы

2022-12-01 21:55 UTC, vdromanov commented on wb/device_manager/mqtt_rpc.py
> +        self.mqtt_connection.disconnect()
готово

+ чищу топики, как Пётр заметил

2022-12-01 22:12 UTC, vdromanov commented on wb/device_manager/main.py
> +                        await self.publish_state_produce()
готово

2022-12-01 22:12 UTC, vdromanov commented on wb/device_manager/main.py
> +        async for port in self._get_ports():
готово

2022-12-01 22:14 UTC, vdromanov commented on wb/device_manager/main.py
> +        async for port in self._get_ports():
а кривые настройки uart при запуске через gather починились - не внедрением очередей: похоже, корень зла - сам асинхронный дизайн; починилось вытаскиванием настроек максимально близко к сканированию (пока поток выполнения не ускакал далеко)

2022-12-02 04:14 UTC, webconn requested changes
Стало уже поинтереснее

2022-12-02 04:14 UTC, webconn commented on tests/checklist.md
> +        * периодически публикует json всего состояния в /wb-device-manager/state
Это ж неправда, там не периодическая публикация должна быть, а в процессе сканирования. И надо описать, что триггерит сканирование портов

2022-12-02 04:14 UTC, webconn commented on wb/device_manager/main.py
>      devices: set[DeviceInfo] = field(default_factory=set)
Кстати, я тут подумал, а эта штука не будет нам перемешивать результат на выходе время от времени при добавлении устройства? Там же хэш-таблица внутри

2022-12-02 04:14 UTC, webconn commented on wb/device_manager/main.py
> +                    "progress" : 0
Ещё список девайсов тут надо было подчистить (+ тесткейс про это)

2022-12-02 04:14 UTC, webconn commented on wb/device_manager/mqtt_rpc.py
> +            self.mqtt_connection.publish(topic, payload=None, retain=True)
Тут после этого ещё надо сделать `wait_for_publish()` от каждого возвращаемого значения `publish` (возвращается что-то типа future)

2022-12-02 07:57 UTC, vdromanov commented on wb/device_manager/main.py
>      devices: set[DeviceInfo] = field(default_factory=set)
а вот будет....
set же не ordered

предлагаю на этапе сборки+отправки state - сортировать по last_scan_ts

2022-12-02 08:28 UTC, KraPete commented on wb/device_manager/main.py
>      devices: set[DeviceInfo] = field(default_factory=set)
У нас же uuid везде, пусть перемешивает

2022-12-02 12:18 UTC, vdromanov commented
Женя хочет сейчас:

- убрать перебор стопбитиков
- брать порты уже из rpc к сериалу

2022-12-02 12:42 UTC, KraPete commented
Ещё в ответе можно не слать поля с `null`. Размер будет меньше, а фронту пофиг

2022-12-06 23:29 UTC, vdromanov commented on wb/device_manager/main.py
> +                    "progress" : 0
готово
дописал в сценарии

2022-12-06 23:29 UTC, vdromanov commented on wb/device_manager/mqtt_rpc.py
> +            self.mqtt_connection.publish(topic, payload=None, retain=True)
готово

2022-12-06 23:57 UTC, evgeny-boger requested changes
прогресс у меня тикает до 24% вместо 100%

2022-12-07 00:11 UTC, evgeny-boger commented
кажется, пора вместо "Scanned device" начать выдавать что-то осмысленное. Например завести базу сигнатур и по ним писать настоящее название устройства. А если неизвестно - то саму сигнатуру.

2022-12-07 06:59 UTC, sikmir commented
```
# mqtt-rpc-client -d wb-device-manager -s bus-scan -m Scan
'Ok'
```

2022-12-07 08:37 UTC, sikmir commented
> а в чём проблема? (желательно - с mqtt-топиком)

Не, тут все норм.

2022-12-08 09:53 UTC, vdromanov commented on debian/control
> +Depends: ${python3:Depends}, ${misc:Depends}, python3-mqttrpc (>= 1.1.5), wb-mqtt-serial (>= 2.77.6), python3-wb-mcu-fw-updater (>= 1.6.1)
так ты же там "request timed out" добавил
по которому девайс_менеджер смотрит, что устройство не ответило

пока error codes в сериале не работают

2022-12-08 22:26 UTC, vdromanov commented on tests/busscanner_test.py
> +        self.mock_response("")  # TODO: empty rpc-answer means no support in wb-mqtt-serial; maybe custom error?
да, какая-то странная туду; убрал

а по поведению - у нас свалится rpc_timeout запроса к сериалу

2022-12-08 22:26 UTC, vdromanov commented on tests/checklist.md
> +        * периодически публикует json всего состояния в /wb-device-manager/state
готово

2022-12-08 22:27 UTC, vdromanov commented on wb/device_manager/main.py
> +        ec = EXIT_UNKNOWN
готово

2022-12-08 22:27 UTC, vdromanov commented on wb/device_manager/main.py
> +EXIT_UNKNOWN = 4
готово

2022-12-08 22:27 UTC, vdromanov commented on wb/device_manager/main.py
> +def count_any_iterable(iterable):
убрал

ну да, сам себя перехитрил

2022-12-08 22:27 UTC, vdromanov commented on wb/device_manager/main.py
> +        len_iterable = count_any_iterable(iterable)
готово

2022-12-08 22:27 UTC, vdromanov commented on wb/device_manager/main.py
> +    async def _get_all_uart_params(self, bds=ALLOWED_BAUDRATES, parities=ALLOWED_PARITIES.keys(),
готово

2022-12-08 22:27 UTC, vdromanov commented on wb/device_manager/main.py
> +        return [port["path"] for port in response]  # TODO: use serial_params from response?
убрал

2022-12-08 22:30 UTC, vdromanov commented on wb/device_manager/main.py
> +    async def launch_scan(self):
кажется, нужен

специально делали [AMQTTRPCResponseManager](https://github.com/wirenboard/python-mqtt-rpc/blob/0e4be374a0058f04df3d0ed81ec53fdd3ffc64a3/mqttrpc/manager.py#L101), который ест async-функции

другой вопрос - что из ситуации в данный момент - можно ResponseManager взять и синхронный (т.к. он - только запускает таску)

предлагаю оставить, как сейчас, т.к. есть не просит; как бонус - получаем лёгкое "проксирование" недолгих rpc-запросов куда-нибудь

2022-12-08 22:30 UTC, vdromanov commented on wb/device_manager/main.py
> +            return "Ok"
нам бы где-то хранить mqtt-топики и привязанные к ним работающие async-таски (а не сам коллбек-запускатор)
написал туду про это

2022-12-08 22:30 UTC, vdromanov commented on wb/device_manager/main.py
> +        """
готово

2022-12-08 22:31 UTC, vdromanov commented on wb/device_manager/main.py
> +            if progress_precent > self.state.progress:
готово

2022-12-08 22:31 UTC, vdromanov commented on wb/device_manager/main.py
> +    async def _all_devices(self):
убрал вообще

это лишний endpoint оставался для потыкать

2022-12-08 22:31 UTC, vdromanov commented on wb/device_manager/mqtt_rpc.py
> +    _WB_DEVICES_RESPONSE_TIME = 8E-3  # wb devices with old fws
это - моя странная идея

убрал внутрь _calculate_...

2022-12-08 22:31 UTC, vdromanov commented on wb/device_manager/mqtt_rpc.py
> +        overall_serial_rpccall_processing = rpc_call_timeout - 1.0  # network roundtrip
готово

2022-12-08 22:31 UTC, vdromanov commented on wb/device_manager/mqtt_rpc.py
> +        logger.debug("Bind on_connect callback to %s", self.mqtt_hostport_str)
убрал

2022-12-08 22:31 UTC, vdromanov commented on tests/checklist.md
> +* пакет успешно устанавливается на WB с релизом > wb-2207; **не** устанавливается на <= wb-2207
готово

2022-12-08 22:32 UTC, vdromanov commented on tests/checklist.md
> +### Интерфейс rpc наружу
дописал всякого

2022-12-09 06:31 UTC, webconn commented on wb/device_manager/main.py
> +    async def launch_scan(self):
Убедил

2022-12-09 06:31 UTC, webconn commented on wb/device_manager/main.py
> +            return "Ok"
Что ты имеешь в виду? У нас информация о запущенном сканировании уже есть в JSON, все остальные таски также должны быть додумываемы исходя из JSON.

2022-12-09 07:55 UTC, vdromanov commented on wb/device_manager/main.py
> +            return "Ok"
потом добавится прошивка устройства

но наверное, пока что можно об этом не думать
но туду - оставил бы

2022-12-09 07:55 UTC, vdromanov commented on tests/busscanner_test.py
> +            1200 : minimalmodbus._calculate_minimum_silent_period(1200),
а чем мешает?
если константы добавлять - придётся над округлением думать
![2022-12-09_10-53-07](https://user-images.githubusercontent.com/25829054/206652542-e6c6ded8-f6e5-48af-a8f2-24e56b775a64.png)


предлагаю оставить, как есть; т.к. это - еще и дополнительное напоминание выпилить minimalmodbus

2022-12-09 07:55 UTC, vdromanov commented on wb/device_manager/main.py
> +    error: str = None
готово в https://github.com/wirenboard/wb-device-manager/pull/5

2022-12-12 04:31 UTC, webconn commented on tests/busscanner_test.py
> +            1200 : minimalmodbus._calculate_minimum_silent_period(1200),
А числа с плавающей точкой вообще некорректно сравнивать на равенство, их обычно сравнивают с заданной точностью, см. `assertAlmostEqual`

2022-12-12 04:33 UTC, webconn approved these changes

2022-12-12 05:36 UTC, KraPete requested changes
Женя просил убрать признак того, что устройство не опрашивается. Мы же сейчас не получаем его от `wb-mqtt-serial`. В результате оно только глаза мозолить будет

2022-12-14 11:05 UTC, vdromanov commented
@KraPete ошибочки не такие страшные (как обсуждали в телеге)
![2022-12-14_14-03-20](https://user-images.githubusercontent.com/25829054/207579076-a230f633-3715-4fe1-90f3-53c48f92c2ad.png)
![2022-12-14_14-02-47](https://user-images.githubusercontent.com/25829054/207579080-a757658d-6fd0-481c-a597-4bac5688f74e.png)

2022-12-14 11:08 UTC, vdromanov commented
последний статус: из чек-листа
![2022-12-14_14-06-43](https://user-images.githubusercontent.com/25829054/207579414-75980974-b92f-4c14-ac56-9d1322640858.png)

осталось - "Перевести считывание свойств устройств на запросы быстрого модбаса (исправить работу при коллизиях slave id)"

решили сделать отдельным PRом, чтобы не растягивать этот

2022-12-19 06:18 UTC, KraPete commented on tests/checklist.md
> +* корректный exit-code (остановить systemd-сервис; запускать утилиту вручную):
У нас остальные сервисы циклично перезапускаются, ожидая москиту

2022-12-19 06:19 UTC, KraPete commented on tests/checklist.md
> +* при остановке mosquitto, сервис wb-device-manager остаётся running; перезапуск сервиса приводит к failed
У нас остальные сервисы циклично перезапускаются через systemd, ожидая москиту

2022-12-19 06:20 UTC, KraPete commented on tests/checklist.md
> +* при запуске сервис шлёт в топик состояния пустой state
Не пустой же. А с пустым списком устройств

2022-12-19 06:21 UTC, KraPete commented on tests/checklist.md
> +        * пока идёт сканирование - возвращает ошибку 33100 на повторные вызовы
А зачем?

2022-12-19 06:26 UTC, KraPete commented on wb/device_manager/main.py
> +            timeout=1.0  # rpc call goes around scheduler queue => relatively small
Я не люблю использовать числа для временных интервалов. Вот этот 1 - это 1 день, 1 - час, 1 - наносекунда?

2022-12-19 06:29 UTC, KraPete commented on wb/device_manager/main.py
> +                err_to_webui = "Check, wb-mqtt-serial is running"
Тексты ошибок надо переводить на русский:
1. Вести общую базу текстов и синхронизировать её
2. Слать тут же русский текст
3. Делать код ошибки, тогда по коду, можно искать перевод. Это чуть лучше чем п.1

2022-12-19 23:23 UTC, vdromanov commented on tests/checklist.md
> +* при запуске сервис шлёт в топик состояния пустой state
готово

2022-12-19 23:23 UTC, vdromanov commented on tests/checklist.md
> +        * пока идёт сканирование - возвращает ошибку 33100 на повторные вызовы
кажется, так изначально решили

2022-12-19 23:23 UTC, vdromanov commented on wb/device_manager/main.py
> +            timeout=1.0  # rpc call goes around scheduler queue => relatively small
не видел, чтобы в питоне использовали timedelta для таких целей
=> добавил комментик про секунду, т.к. с timedelta и получается неканонично, и дополнительный импорт тянуть

2022-12-19 23:23 UTC, vdromanov commented on wb/device_manager/main.py
> +                err_to_webui = "Check, wb-mqtt-serial is running"
обсудили - решили околовариант 3; делаем отдельным PR

2022-12-19 23:25 UTC, vdromanov commented
решили сейчас влить, чтобы PR не разрастался

2022-12-19 23:25 UTC, merged