Feature/new errors
wirenboard/wb-device-manager pull request #6
Opened 2022-12-20 13:51 UTC by vdromanov

ошибочки в webui для перевода, как обсуждали: id и message

2022-12-21 04:01 UTC, KraPete requested changes
1. Хочу табличку с возможными типами ошибок
2. Хочу описание случая, когда `id == null`

2022-12-21 04:01 UTC, KraPete commented on README.md
> +* ошибки в понятном человеку виде отображаются в webui
Я бы тут оставил только про то, как формируются `id` ошибок, и как их в логах посмотреть. Остальное надо в сценарии проверки `homeui`.

2022-12-22 07:26 UTC, webconn reviewed
Ещё в чеклист надо заглянуть, там до сих пор про коды ошибок написано

2022-12-25 16:34 UTC, vdromanov commented on README.md
> +        "message": "RPC call to wb-mqtt-serial timed out"
готово

2022-12-25 16:34 UTC, vdromanov commented on README.md
> +                "message": "Modbus communication failed. Check logs for more info"
готово

2022-12-25 16:34 UTC, vdromanov commented on README.md
> +                        "message": "FW update failed. Check logs for more info"
а этого и нет, т.к. пока не умеем обновлять прошивки; написал комментик

2022-12-25 16:34 UTC, vdromanov commented on README.md
> +* ошибки в понятном человеку виде отображаются в webui
готово

2022-12-25 16:35 UTC, vdromanov commented
табличку с ошибками сделал; чеклист - поправил

2022-12-26 05:58 UTC, KraPete requested changes
Осталось про `id == null`. Такое возможно?

2022-12-26 07:56 UTC, vdromanov commented
> Осталось про `id == null`. Такое возможно?

уже нет => вот и не написал

2022-12-26 08:00 UTC, KraPete approved these changes

2022-12-26 08:04 UTC, merged