Feature/devices ordering
wirenboard/wb-device-manager pull request #9
Opened 2022-12-22 15:43 UTC by vdromanov

- устройства в жсоне появляются в порядке их арбитража
- проверяем коллизии serial-настроечек: уникальным должно быть (slaveid, port, настройки_связи)

2022-12-23 07:17 UTC, webconn requested changes

2022-12-23 07:17 UTC, webconn commented on wb/device_manager/main.py
> +                        serial_params.append(connection_params)
Что-то сложно. А почему бы постоянно этот словарь не хранить и не проверяться от него?

```python3
  devices_by_connection = defaultdict(list)
  
  while True:
    event = await self.state_update_queue.get()
    try:
      if isinstance(event, DeviceInfo):
        state.devices.append(event)
        neighbors = devices_by_connection[(device_info.cfg, device_info.port)]
        neighbors.append(event)
        if len(neighbors) >= 2:
          for entry in neighbors:
            entry.slave_id_collision = True
      elif isinstance(event, dict):
        if "devices" in event and not event["devices"]:
          devices_by_connection.clear()
        ...
```

Можно написать ещё аккуратней, если постараться

2022-12-25 19:32 UTC, vdromanov commented on wb/device_manager/main.py
> +                        serial_params.append(connection_params)
у меня была идея проверять collisions, когда меняется slaveid (не случилось ли новых)

но замену slaveid пока не завезли; мб потом по-другому вообще сделаем => поправил на твой более простой вариант

2022-12-26 06:53 UTC, webconn commented on wb/device_manager/main.py
> +                        serial_params.append(connection_params)
Так и в моём варианте тебе ничего не мешает проверять коллизии

2022-12-26 06:55 UTC, webconn reviewed
И ещё хорошо было бы юнит-тест сюда добавить

2022-12-26 08:20 UTC, vdromanov commented
обсудили в телеге; решили сделать юнит-тесты потом, т.к. пока что - не нравится то, что под капотом

(придумать доступ к state_json снаружи)

2022-12-26 08:25 UTC, webconn approved these changes

2022-12-26 08:27 UTC, merged